package br.jus.tjce.cayenne.TutorialCayenne.persistence.auto;

import org.apache.cayenne.CayenneDataObject;

import br.jus.tjce.cayenne.TutorialCayenne.persistence.Artista;
import br.jus.tjce.cayenne.TutorialCayenne.persistence.Galeria;

/**
 * Class _Pintura was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Pintura extends CayenneDataObject {

	private static final long serialVersionUID = -6143346658541384689L;
	public static final String NOME_PROPERTY = "nome";
    public static final String RELACAO_ARTISTA_PROPERTY = "relacaoArtista";
    public static final String RELACAO_GALERIA_PROPERTY = "relacaoGaleria";

    public static final String ID_PK_COLUMN = "id";

    public void setNome(String nome) {
        writeProperty("nome", nome);
    }
    public String getNome() {
        return (String)readProperty("nome");
    }

    public void setRelacaoArtista(Artista relacaoArtista) {
        setToOneTarget("relacaoArtista", relacaoArtista, true);
    }

    public Artista getRelacaoArtista() {
        return (Artista)readProperty("relacaoArtista");
    }


    public void setRelacaoGaleria(Galeria relacaoGaleria) {
        setToOneTarget("relacaoGaleria", relacaoGaleria, true);
    }

    public Galeria getRelacaoGaleria() {
        return (Galeria)readProperty("relacaoGaleria");
    }


}
